### ISSUE TITLE
Not sure what needs to be done

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/operators#29]
Many of my recent lessons on GitHub are 1 or 2 commits "ahead of learn-co-students:master." No matter what I do--via Nitrous or command line, I can't seem to get it even with the master.

Am I doing it wrong? Sorry about the endless pull requests (along w other newbie errors).

**Comment by AnnJohn** [comment]
Hi @CodeByLine that's normal since your new branch has commits that you've made when working on the lab. For that reason the commit history should always be ahead since you're not making any changes on learn-co-students:master but instead on your forked version of it. So yes, you're doing it just fine.

**Comment by CodeByLine** [comment]
Thanks!!!
