### ISSUE TITLE
Bug in test for ternary operator

### ISSUE THREAD

**Issue by Alex3921** [learn-co-curriculum/operators#39]
The code seems to be right but the test doesn't recognize the **"?"**. Can you please assist as the issue doesn't allow me to complete the lab.

![ternary_test_bug](https://user-images.githubusercontent.com/60633447/109547446-fd63fd80-7a90-11eb-949c-16144430fa72.png)

**Comment by lizbur10** [comment]
Hi there! I think the problem here may be the method calls at the bottom of your file. Try deleting or commenting out lines 15-21 and rerunning the test. 

If that doesn't fix the issue, I recommend that you post the question on [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. 

Good luck!
